name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3.5.1
        with:
          always-auth: true
          node-version: 14
          registry-url: "https://registry.npmjs.org"
          scope: "@demartini"

      - name: Cache Node Modules
        uses: actions/cache@v3.2.6
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Config Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bootstrap Lerna
        run: yarn lerna:bootstrap:ci

      - name: Bump Versions and Publish Packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn lerna:version
          yarn lerna:publish
